version: '3.0'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_CREATE_TOPICS: "test-topic:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        #volumes:
        #  - /var/run/docker.sock:/var/run/docker.sock
    spark-runtime:
        build: .
        image: pyspark-kafka
        container_name: pyspark-kafka
        links:
            - kafka:kafka
            - mongodb:mongodb
        volumes:
            - ./data:/data
        ports:
            - 4040:4040
    mongodb:
        image: mongo
        container_name: mongodb
        hostname: mongodb
        #volumes:
        #  - ./mongodb/data/db/:/data/db
        #env_file:
        #  - mongodb/mongo.env
        environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin

        ports:
        - '27017-27019:27017-27019'